version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-survey_db}
      POSTGRES_USER: ${POSTGRES_USER:-survey_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-survey_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-survey_user} -d ${POSTGRES_DB:-survey_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-survey_user}:${POSTGRES_PASSWORD:-survey_password}@db:5432/${POSTGRES_DB:-survey_db}"
      SESSION_SECRET: ${SESSION_SECRET:-your-secret-at-least-32-characters-long-change-this}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node server.js
      "

volumes:
  postgres_data: