/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Options {
  active: Generated<boolean>;
  added_at: Timestamp | null;
  description: string | null;
  label: string;
  order: number;
  question_slug: string;
  slug: string;
}

export interface Questions {
  active: Generated<boolean>;
  added_at: Timestamp | null;
  description: string | null;
  multiple_max: number | null;
  order: number;
  randomize: Generated<boolean>;
  section_slug: string;
  slug: string;
  title: string;
  type: string;
}

export interface Responses {
  comment: string | null;
  experience_awareness: number | null;
  experience_sentiment: number | null;
  freeform_response: string | null;
  iso_week: number;
  iso_year: number;
  multiple_option_slugs: string[] | null;
  multiple_writein_responses: string[] | null;
  numeric_response: Numeric | null;
  option_slug: Generated<string>;
  question_slug: string;
  session_id: string;
  single_option_slug: string | null;
  single_writein_response: string | null;
  skipped: Generated<boolean>;
}

export interface Sections {
  active: Generated<boolean>;
  added_at: Timestamp | null;
  description: string | null;
  order: number;
  slug: string;
  title: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  id: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  options: Options;
  questions: Questions;
  responses: Responses;
  sections: Sections;
  sessions: Sessions;
}
